config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  post 'home/create_subscriber'
  post 'home/feedback_subscriber'
  get 'home/ror'
  post 'home/create_quote'
  get 'home/contact'
  post 'home/create_contact'
  get 'home/about'
  get '/terms_condition' => 'home#terms_condition'
  get '/privacy_policy' => 'home#privacy_policy'
  get 'home/java'
  get 'home/unsubscribe'
  patch 'home/update_subscription'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
	validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@subscriber = 200 + Subscriber.where(active: true).count
  	@new_subscriber = Subscriber.new
    @feedback = Feedback.new
  end

  def contact
    @contact = Feedback.new
  end

  def create_contact
    @contact = Feedback.new(contact_params);
    respond_to do |format|
      if @contact.save
        ClientQuoteMailer.contact_mail(@contact).deliver_later
        @contact = Feedback.new
        format.html { redirect_to root_path, notice: 'Sucessfully sent contact .Thanks for contacting us.We will get back to you soon' }
        format.js
      else
        @contact = Feedback.new
        format.html { render :contact }
        format.js
      end
    end
  end

  def create_subscriber
  	@new_subscriber = Subscriber.new(subscriber_params);
    respond_to do |format|
      if @new_subscriber.save
      	@subscriber = 200 + Subscriber.where(active: true).count
        @unsubscribe = Rails.application.message_verifier(:unsubscribe).generate(@new_subscriber.id)
        ClientQuoteMailer.subscribe_mail(@new_subscriber,@unsubscribe).deliver_later
      	@new_subscriber = Subscriber.new
        format.html { redirect_to root_path, notice: 'Sucessfully Subscribed Newsletter' }
        format.js
      else
      	@subscriber = 200 + Subscriber.where(active: true).count
        format.html { render :index }
        format.js
      end
    end
  end
  def feedback_subscriber
    @feedback = Feedback.new(feedback_params);
    respond_to do |format|
      if @feedback.save
        @feedback = Feedback.new
        format.html { redirect_to root_path, notice: 'Sucessfully sent feedback .Thanks for your valuable time' }
        format.js
      else
        format.html { render :index }
        format.js
      end
    end
  end
  def ror
    @quote =  Quote.new
  end

  def create_quote
    @quote = Quote.new(quote_params);
    respond_to do |format|
      if @quote.save
        ClientQuoteMailer.client_quote(@quote).deliver_later
        @quote = Quote.new
        format.html { redirect_to home_ror_path, notice: 'Sucessfully sent quote. We will contact with you soon.' }
        format.js
      else
        format.html { render :ror }
        format.js
      end
    end
  end
  def about
  
  end
  def terms_condition
    
  end
  def privacy_policy
    
  end
  def java
    
  end

  def unsubscribe
    subscriber = Rails.application.message_verifier(:unsubscribe).verify(params[:id])
    @subscriber = Subscriber.find(subscriber)
  end

  def update_subscription
    @subscriber = Subscriber.find(params[:id])
    if @subscriber.update(subscriber_params)
      @unsubscribe = Rails.application.message_verifier(:unsubscribe).generate(@subscriber.id)
      ClientQuoteMailer.subscribe_mail(@subscriber,@unsubscribe).deliver_later
      flash[:notice] = 'Subscription Cancelled' 
      redirect_to root_url
    else
      flash[:alert] = 'There was a problem'
      render :unsubscribe
    end
  end

  private

  def subscriber_params
    params.fetch(:subscriber, {}).permit(:email,:active)
  end
  def feedback_params
    params.fetch(:feedback, {}).permit(:name,:email,:phone,:message)
  end
  def quote_params
    params.fetch(:quote, {}).permit(:name,:email,:phone,:timing,:message)
  end
  def contact_params
    params.fetch(:feedback, {}).permit(:name,:email,:phone,:message,:from)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_contact_message.html.erb
<div class="bs-example alerts">
	<div class="alert alert-success message-top">
		<a href="#" class="close" data-dismiss="alert">&times;</a>
		<strong>Success!</strong> Thanks for contacting us.We will get back to you soon.
	</div>
</div> 

app/views/home/_feedback_quote.html.erb
<!-- Feedback Form -->
<div class="g-bg-color--sky-light">
    <div class="container g-padding-y-80--xs g-padding-y-125--sm">
        <div class="g-text-center--xs g-margin-b-80--xs">
            <p class="text-uppercase g-font-size-14--xs g-font-weight--700 g-color--primary g-letter-spacing--2 g-margin-b-25--xs">Feedback</p>
            <h2 class="g-font-size-32--xs g-font-size-36--md">Send us a note</h2>
        </div>
        <div id="feedback-message"></div>
        <%= form_for @feedback,  :url => (home_feedback_subscriber_path),:html => { :id =>'feedback',:role=>'form'},:remote => true do |f| %>
            <div class="row g-margin-b-40--xs">
                <div class="col-sm-6 g-margin-b-20--xs g-margin-b-0--md">
                    <div class="g-margin-b-20--xs">
                        <%= f.text_field :name, class: 'form-control s-form-v2__input g-radius--50',placeholder: "* Name",required: true %>
                    </div>
                    <div class="g-margin-b-20--xs">
                        <%= f.email_field :email, class: 'form-control s-form-v2__input g-radius--50',placeholder: '* Email',required: true%>
                    </div>
                    <%= f.text_field :phone, class: 'form-control s-form-v2__input g-radius--50',placeholder: "* Phone",required: true%>
                </div>
                <div class="col-sm-6">
                    <%= f.text_area :message, class: 'form-control s-form-v2__input g-radius--10 g-padding-y-20--xs', :rows => 9,placeholder: '* Your message',required: true %>
                </div>
            </div>
            <div class="g-text-center--xs">
                <%= f.button(type: "submit", class: "text-uppercase s-btn s-btn--md s-btn--primary-bg g-radius--50 g-padding-x-80--xs") do %>
                Submit
                <% end %>
            </div>
        <% end %>
    </div>
</div>
        <!-- End Feedback Form -->

app/views/home/_quote.html.erb
<!-- Contact -->
<div class="s-promo-block-v7 g-bg-position--center g-bg-color--dark-light" style="background: url(<%= asset_path '1920x1080/05.jpg' %>) no-repeat;">
    <div class="g-container--sm g-padding-y-80--xs g-padding-y-125--xsm">
        <div class="g-text-center--xs g-margin-b-60--xs">
            <h2 class="g-font-size-32--xs g-font-size-36--md g-color--white">GET IN TOUCH WITH US</h2>
            <p class="text-uppercase g-font-size-14--xs g-font-weight--700 g-color--white-opacity g-letter-spacing--2 g-margin-b-25--xs">Let’s build something great, together.</p>
        </div>
        <%= form_for @quote,  :url => (home_create_quote_path),:html => { :id =>'quote',:role=>'form',:class => 'center-block g-width-500--sm g-width-550--md'},:remote => true do |f| %>
            <div class="g-margin-b-30--xs">
                <%= f.text_field :name, class: 'form-control s-form-v3__input',placeholder: "* Name",required: true %>
            </div>
            <div class="row g-margin-b-50--xs">
                <div class="col-sm-6 g-margin-b-30--xs g-margin-b-0--md">
                    <%= f.email_field :email, class: 'form-control s-form-v3__input',placeholder: '* Email',required: true%>
                </div>
                <div class="col-sm-6">
                    <%= f.text_field :phone, class: 'form-control s-form-v3__input',placeholder: "* Phone",required: true%>
                </div>
            </div>
            <div class="g-margin-b-30--xs">
                <%= f.text_field :timing, class: 'form-control s-form-v3__input',placeholder: "* Best time to reach you (Ex Monday 11 AM EST)",required: true%>
            </div>
            <div class="g-margin-b-80--xs">
                <%= f.text_area :message, class: 'form-control s-form-v3__input', :rows => 6,placeholder: '* Your message',required: true %>
            </div>
            <div class="g-text-center--xs">
                <%= f.button(type: "submit", class: "text-uppercase s-btn s-btn--md s-btn--white-brd g-radius--50 g-padding-x-70--xs g-margin-b-20--xs") do %>
                Submit
                <% end %>
            </div>
        <% end %>
        <div id="quote-message"></div>
    </div>
</div>
<!-- End Contact -->

app/views/home/_quote_message.html.erb
<div class="bs-example">
	<div class="alert alert-success message-top">
		<a href="#" class="close" data-dismiss="alert">&times;</a>
		<strong>Success!</strong> Sucessfully sent quote. We will contact with you soon.
	</div>
</div>

app/views/home/_subscribe_form.html.erb
<%= form_for @subscriber,  :url => (home_update_subscription_path(id: @subscriber.id)),:html => { :id =>'contact',:role=>'form',:class => 'center-block g-width-500--sm g-width-550--md'} do |f| %>
    
    <%= f.hidden_field :active, :value => true%>
    <div id="contact-message"></div>
    <div class="g-text-center--xs">
        <%= f.button(type: "submit", class: "text-uppercase s-btn s-btn--md s-btn--white-bg g-radius--50 g-padding-x-70--xs g-margin-b-20--xs") do %>
                Subscribe
        <% end %>
    </div>
<% end %>

app/views/home/_subscriber_count.html.erb
<p class="text-uppercase g-font-size-14--xs g-font-weight--700 g-color--white-opacity g-letter-spacing--2 g-margin-b-25--xs">Subscribe</p>
<h2 class="g-font-size-32--xs g-font-size-36--md g-color--white">Join Over <%= @subscriber %>+ People</h2>

app/views/home/_subscriber_error_message.html.erb
<% if @new_subscriber.errors.any? %>
<% @new_subscriber.errors.full_messages.each do |message| %>
<div class="bs-example">
	<div class="alert alert-warning message-top">
		<a href="#" class="close" data-dismiss="alert">&times;</a>
		<strong>Warning!</strong> <%= message %>
	</div>
</div>
<% end %>
<% end %>

app/views/home/_subscription_email.html.erb
<div class="col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
	<%= form_for @new_subscriber,  :url => (home_create_subscriber_path),:html => {:class => 'input-group', :id =>'subscriber',:role=>'form'},:remote => true do |f| %>
	<%= f.email_field :email, class: 'form-control s-form-v1__input g-radius--left-50',placeholder: 'Enter your email'%>
	<span class="input-group-btn">
		<%= f.button(type: "submit", class: "s-btn s-btn-icon--md s-btn-icon--white-brd s-btn--white-brd g-radius--right-50") do %>
		<i class="ti-arrow-right"></i>
		<% end %>
	</span>
	<% end %>
	<div id="subscriber-message"></div>
</div>

app/views/home/_unsubscribe_form.html.erb
<%= form_for @subscriber,  :url => (home_update_subscription_path(id: @subscriber.id)),:html => { :id =>'contact',:role=>'form',:class => 'center-block g-width-500--sm g-width-550--md'} do |f| %>
    
    <%= f.hidden_field :active, :value => false%>
    <div id="contact-message"></div>
    <div class="g-text-center--xs">
        <%= f.button(type: "submit", class: "text-uppercase s-btn s-btn--md s-btn--white-bg g-radius--50 g-padding-x-70--xs g-margin-b-20--xs") do %>
                Unsubscribe
        <% end %>
        <%= link_to 'Cancel', root_url,:class => "text-uppercase s-btn s-btn--md s-btn--white-bg g-radius--50 g-padding-x-70--xs g-margin-b-20--xs" %>
    </div>
<% end %>

app/views/home/create_contact.js.erb
$('#contact-div').html("<%= j render(:partial => 'contact_form') %>");
<% if @contact.errors.any? %>
	$('#contact-message').html("<%= j render(:partial => 'contact_error_message') %>");
<% else %>
	$('#contact-message').html("<%= j render(:partial => 'contact_message') %>");
<% end %>
$('#contact-message').fadeIn('slow').delay(5000).hide(0);

app/views/layouts/_footer.html.erb
        <!--========== FOOTER ==========-->
        <footer class="g-bg-color--dark">
            <!-- Links -->
            <div class="g-hor-divider__dashed--white-opacity-lightest">
                <div class="container g-padding-y-15--xs">
                    <div class="row">
                        <div class="col-sm-2 g-margin-b-20--xs g-margin-b-0--md">
                            <ul class="list-unstyled g-ul-li-tb-5--xs g-margin-b-0--xs">
                                <li><a class="g-font-size-15--xs g-color--white-opacity" href="/" data-turbolinks="false">Home</a></li>
                                <li><a class="g-font-size-15--xs g-color--white-opacity" href="#">About</a></li>
                                <li><%= link_to "Contacts", home_contact_path,class: 'g-font-size-15--xs g-color--white-opacity', data: { turbolinks: false } %></li>
                            </ul>
                        </div>
                        <div class="col-sm-2 g-margin-b-20--xs g-margin-b-0--md">
                            <ul class="list-unstyled g-ul-li-tb-5--xs g-margin-b-0--xs">
                                <li><%= link_to "Twitter", "https://twitter.com/MtshSoftware",class: 'g-font-size-15--xs g-color--white-opacity', data: { turbolinks: false }, target: :_blank  %></li>
                                <li><%= link_to "Facebook", "https://www.facebook.com/mtshsoftware/",class: 'g-font-size-15--xs g-color--white-opacity', data: { turbolinks: false }, target: :_blank  %></li>
                                <li><%= link_to "Instagram", "https://www.instagram.com/mtshsoftware/",class: 'g-font-size-15--xs g-color--white-opacity', data: { turbolinks: false }, target: :_blank  %></li>
                            </ul>
                        </div>
                        <div class="col-sm-2 g-margin-b-40--xs g-margin-b-0--md">
                            <ul class="list-unstyled g-ul-li-tb-5--xs g-margin-b-0--xs">
                                <li><%= link_to "Privacy Policy", privacy_policy_path,class: 'g-font-size-15--xs g-color--white-opacity', data: { turbolinks: false } %></li>
                                <li><%= link_to "Terms & Conditions", terms_condition_path,class: 'g-font-size-15--xs g-color--white-opacity', data: { turbolinks: false } %></li>
                            </ul>
                        </div>
                        <div class="col-md-4 col-md-offset-2 col-sm-5 col-sm-offset-1 s-footer__logo g-padding-y-50--xs g-padding-y-0--md">
                            <h3 class="g-font-size-18--xs g-color--white">MTSH SOFTWARE &amp; CONSULTANCY PRIVATE LIMITED</h3>
                            <p class="g-color--white-opacity">We are a creative company focusing on code quality, agility &amp; time constraints. Somewhere with Modern Technology Software Hosting (MTSH).</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Links -->

            <!-- Copyright -->
            <div class="container g-padding-y-10--xs">
                <div class="row">
                    <div class="col-xs-6">
                        <a href="/" data-turbolinks="false">
                        	<%= image_tag("2017_09_07_05_07_40_37856_MTSH.png", :alt => "Mtsh logo",class: 'g-width-200--xs g-height-auto--xs') %>
                        </a>
                    </div>
                    <div class="col-xs-6 g-text-right--xs">
                        <p class="g-font-size-14--xs g-margin-b-0--xs g-color--white-opacity-light"><a href="/" data-turbolinks="false">Copyright</a> All Rights Reserved © 2018</a></p>
                    </div>
                </div>
            </div>
            <!-- End Copyright -->
        </footer>
        <!--========== END FOOTER ==========-->
        <!-- Back To Top -->
        <a href="javascript:void(0);" class="s-back-to-top js__back-to-top"></a>

app/views/layouts/_header.html.erb
 <!--========== HEADER ==========-->
 <header class="navbar-fixed-top s-header js__header-sticky js__header-overlay">
    <!-- Navbar -->
    <div class="s-header__navbar">
        <div class="s-header__container">
            <div class="s-header__navbar-row">
                <div class="s-header__navbar-row-col">
                    <!-- Logo -->
                    <div class="s-header__logo">
                        <a href="/" data-turbolinks="false" class="s-header__logo-link">
                           <%= image_tag("2017_09_07_05_07_40_37856_MTSH.png", :alt => "Mtsh Logo",class: 's-header__logo-img s-header__logo-img-default custom-logo') %>
                           <%= image_tag("2017_09_07_05_07_40_37856_MTSH.png", :alt => "Mtsh Logo",class: 's-header__logo-img s-header__logo-img-shrink custom-logo') %>
                       </a>
                   </div>
                   <!-- End Logo -->
               </div>
               <div class="s-header__navbar-row-col">
                <!-- Trigger -->
                <a href="javascript:void(0);" class="s-header__trigger js__trigger">
                    <span class="s-header__trigger-icon"></span>
                    <svg x="0rem" y="0rem" width="3.125rem" height="3.125rem" viewbox="0 0 54 54">
                        <circle fill="transparent" stroke="#fff" stroke-width="1" cx="27" cy="27" r="25" stroke-dasharray="157 157" stroke-dashoffset="157"></circle>
                    </svg>
                </a>
                <!-- End Trigger -->
            </div>
        </div>
    </div>
</div>
<!-- End Navbar -->

<!-- Overlay -->
<div class="s-header-bg-overlay js__bg-overlay">
    <!-- Nav -->
    <nav class="s-header__nav js__scrollbar">
        <div class="container-fluid">
            <!-- Menu List -->                                
            <ul class="list-unstyled s-header__nav-menu">
            <li class="s-header__nav-menu-item"><a class="s-header__nav-menu-link s-header__nav-menu-link-divider -is-active" href="/" data-turbolinks="false">Company</a></li>
            <li class="s-header__nav-menu-item "><p class="s-header__nav-menu-link s-header__nav-menu-link-divider -is-active" >Web Application</p></li>
                <li class="s-header__nav-menu-item">
                <%= link_to "Ruby On Rails", home_ror_path,class: 's-header__nav-menu-link s-header__nav-menu-link-divider', data: { turbolinks: false } %></li>
                <li class="s-header__nav-menu-item">
                <%= link_to "Java", home_java_path,class: 's-header__nav-menu-link s-header__nav-menu-link-divider', data: { turbolinks: false } %></li>
                
            </ul>
            <!-- End Menu List -->

            <!-- Menu List -->                                
            <ul class="list-unstyled s-header__nav-menu">
                <li class="s-header__nav-menu-item"><%= link_to "About", home_about_path,class: 's-header__nav-menu-link s-header__nav-menu-link-divider', data: { turbolinks: false } %></li>
                <li class="s-header__nav-menu-item"><%= link_to "Contacts", home_contact_path,class: 's-header__nav-menu-link s-header__nav-menu-link-divider', data: { turbolinks: false } %></li>
                <li class="s-header__nav-menu-item"><%= link_to "Terms & Conditions", terms_condition_path,class: 's-header__nav-menu-link s-header__nav-menu-link-divider', data: { turbolinks: false } %></li>
                <li class="s-header__nav-menu-item"><%= link_to "Privacy Policy", privacy_policy_path,class: 's-header__nav-menu-link s-header__nav-menu-link-divider', data: { turbolinks: false } %></li>
            </ul>
            <!-- End Menu List -->
        </div>
    </nav>
    <!-- End Nav -->


    <!-- Action -->
    <ul class="list-inline s-header__action s-header__action--rb">
        <li class="s-header__action-item">
            <a class="s-header__action-link" href="https://www.facebook.com/mtshsoftware/" data-turbolinks="false" target="_blank">
                <i class="g-padding-r-5--xs ti-facebook"></i>
                <span class="g-display-none--xs g-display-inline-block--sm">Facebook</span>
            </a>
        </li>
        <li class="s-header__action-item">
            <a class="s-header__action-link" href="https://twitter.com/MtshSoftware" data-turbolinks="false" target="_blank">
                <i class="g-padding-r-5--xs ti-twitter"></i>
                <span class="g-display-none--xs g-display-inline-block--sm">Twitter</span>
            </a>
        </li>
        <li class="s-header__action-item">
            <a class="s-header__action-link" href="https://www.instagram.com/mtshsoftware/" data-turbolinks="false" target="_blank">
                <i class="g-padding-r-5--xs ti-instagram"></i>
                <span class="g-display-none--xs g-display-inline-block--sm">Instagram</span>
            </a>
        </li>
    </ul>
    <!-- End Action -->
</div>
<!-- End Overlay -->
</header>
        <!--========== END HEADER ==========-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js">
  <head>
    <title>Mtsh</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i|Montserrat:400,700" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "//maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_API_KEY']}" %>
    <%= yield :js %>
    <!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBJkq1afpSXP-gOmz5vRk2ocIy4RaHJRvI"></script> -->
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>